# variables:
#   APP_NAME: ${CI_PROJECT_NAME}
#   APP_VERSION: "1.0.0"
#   AWS_ID: ${AWS_ID}
#   AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
#   AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
#   AWS_REGION: us-east-2
#   AWS_PLATFORM: docker


# deploy-dev:
#   stage: deploy
#   image: agoncaruks/aws-elastic-beanstalk-cli:latest
#   script:    
#     - git checkout ${CI_COMMIT_BRANCH}
#     - eb init -i ${APP_NAME} -p ${AWS_PLATFORM} -k ${AWS_ID} --region ${AWS_REGION} --quiet
#     - eb create ${APP_NAME}-${CI_COMMIT_BRANCH} --envvars DJANGO_ENV=dev
#     - eb deploy ${APP_NAME}-${CI_COMMIT_BRANCH} -l ${APP_NAME}-dev-${CI_COMMIT_SHORT_SHA}
#   only:
#       - develop


# deploy-main:
#   stage: deploy
#   image: agoncaruks/aws-elastic-beanstalk-cli:latest
#   script:    
#     - git checkout ${CI_COMMIT_BRANCH}
#     - eb init -i ${APP_NAME} -p ${AWS_PLATFORM} -k ${AWS_ID} --region ${AWS_REGION} --quiet     
#     - eb create ${APP_NAME}-${CI_COMMIT_BRANCH} --envvars DJANGO_ENV=prod
#     - eb deploy ${APP_NAME}-${CI_COMMIT_BRANCH} -l ${APP_NAME}-dev-${CI_COMMIT_SHORT_SHA}
#   only:
#       - main