language: python
python:
  - "3.9"

services:
  - docker

jobs:
  include:
    - stage: build docker image
      before_script: pip install docker-compose
      script:
        - docker-compose build
    - stage: lint
      before_script: pip install docker-compose
      script:
        - docker-compose --env-file .env.dev run app flake8
    - stage: test
      before_script: pip install docker-compose
      script:
        - docker-compose --env-file .env.dev run app sh -c "pytest --cov app"